# # This is a basic workflow to help you get started with Actions
name: CI
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3

      - name: duplicate config.edc for public version
        run: mv logseq/config.public.edn logseq/config.edn && mv logseq/custom.public.css logseq/custom.css

      - uses: logseq/publish-spa@v0.3.0

      - name: Inject Giscus Script
        run: sed -i "s@</body>@$( cat logseq/giscus.html | tr '\n' ' ' | sed 's@&@\\&@g' )</body>@"  www/index.html

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
          single-commit: true